//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IB_Math.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaigtestAn
    {
        public int DiagtestAns_id { get; set; }
        public string Diagtest_Score { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<System.DateTime> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedBy { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> Course_Id { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
