//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IB_Math.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiagnosticTest()
        {
            this.UsersDiagnostictests = new HashSet<UsersDiagnostictest>();
        }
    
        public int Course_id { get; set; }
        public int Diagtest_id { get; set; }
        public string Diagtest_name { get; set; }
        public string Diagtest_que { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public int Weightage { get; set; }
        public Nullable<System.DateTime> CraetedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<System.DateTime> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedBy { get; set; }
        public Nullable<System.DateTime> Deletedby { get; set; }
        public string Diagtest_answer { get; set; }
        public Nullable<bool> QueType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersDiagnostictest> UsersDiagnostictests { get; set; }
        public virtual Cours Cours { get; set; }
    }
}
